version: '2'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-heroku
    command: bash -c "npm install && npm start"
    working_dir: /app
    volumes:
      - '.:/app'
    ports:
      - '127.0.0.1:4000:4000'
